//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int Id { get; set; }
        public Nullable<int> Bravoury { get; set; }
        public Nullable<int> Crazyness { get; set; }
        public Nullable<int> PV { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> HouseID { get; set; }
    }
}
