//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class GeniusDBEntities : DbContext
    {
        public GeniusDBEntities()
            : base("name=GeniusDBEntities")
        {
            //Connexion
            /*using (SqlConnection connection = new SqlConnection())
            {
                string cs = "Data Source=(LocalDB)/MSSQLLocalDB;AttachDbFilename=C:/Users/Bane/Desktop/Github/application-web/ProjetThronesTournamentSolution/GeniusDB.mdf;Integrated Security=True;Connect Timeout=30";
                connection.ConnectionString = cs;
                connection.Open();
                Console.WriteLine("State: {0}", connection.State);
                Console.WriteLine("ConnectionString: {0}", connection.ConnectionString);
            }
            */
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<Territory> Territory { get; set; }
    }
}
